### ISSUE TITLE
Can't download video with latest version of Protect on UDM-Pro

### ISSUE THREAD

**Issue by TokugawaHeavyIndustries** [unifi-toolbox/unifi-protect-video-downloader#33] opened 2020-07-25 14:49 UTC
Using both download and sync, the program errors out and only downloads a few minutes of footage:

`mattperry@docker-temp:~/unifi-protect-video-downloader$ sudo docker run --network=unifi-protect-video-downloader_default --volume /mnt/saturnv/moxie:/downloads unifitoolbox/protect-archiver sync --cameras="xxxxxxx" --address="unifi-udm-api-proxy" --username xxxxxxx --password xxxxxxxx --ignore-failed-downloads /downloads`

`Downloading footage for camera 'Back Living Room' (xxxxxxxxxx)
Downloading video for time range 2020-04-09 17:00:00 - 2020-04-09 17:59:58 to /downloads/2020/04/09/Back Living Room (03ee)/Back Living Room (03ee) - 2020-04-09 - 17.00.00.mp4
Download successful after 19s (187.89 mb, 9.67 mbps)
Downloading footage for camera 'Back Living Room' (xxxxxxxxxx)
Downloading video for time range 2020-04-09 18:00:00 - 2020-04-09 18:59:58 to /downloads/2020/04/09/Back Living Room (03ee)/Back Living Room (03ee) - 2020-04-09 - 18.00.00.mp4
Failed to sync camera Back Living Room - continuing to next device
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/sync.py", line 55, in run
    self.client.download_footage(interval_start, interval_end, camera)
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/client.py", line 390, in download_footage
    self.download_file(address, filename)
  File "/usr/local/lib/python3.8/site-packages/protect_archiver/client.py", line 175, in download_file
    data.get("error") or data or "(no information available)"
AttributeError: 'NoneType' object has no attribute 'get'
Getting camera list
1 files downloaded (187.89 mb), 0 files skipped, 1 files total`

Using download instead of sync, we get the following:

"Non-monotonic timestamp provided."

**Comment by danielfernau** [comment] 2020-07-27 22:55
Hi there!
Thanks for reporting this issue, I'll look into it as soon as I find some time to do so.
For me this error looks like it might be caused by a non-existent video segment on the UDM, which in turn results in the downloader module failing while trying to locate/download it.
Please keep in mind that using the software in combination with the UDM proxy might not work for some system setups and scenarios. However, if I manage to replicate the issue with my test setup over here and find a solution, I'll let you know!

**Comment by touche112** [comment] 2020-07-28 13:33
Hey @danielfernau , thanks for the reply back.  I am happy to assist in troubleshooting or testing if needed.

I did try to download the segment in question from the web UI and it downloaded ok.

**Comment by ntableman** [comment] 2020-10-21 18:01
I think the issue is that you have hardcoded the port, remove that and it works.

**Comment by danielfernau** [comment] 2020-10-21 19:21
@ntableman As far I remember there's no hard-coded port, neither in v1.x nor in v2.x -- there's only a default port (7443) that is being used if the `--port` parameter is not provided set via command line. We're currently working on replacing and improving the authentication/session part anyways, so all that should be resolved in one of the next versions 🙂

**Comment by danielfernau** [comment] 2021-05-02 11:46
Hi @TokugawaHeavyIndustries 

A new release – [v2.0.1](https://github.com/unifi-toolbox/unifi-protect-video-downloader/releases/tag/v2.0.1) – is now available. Please have a look if the problem you've reported here still occurs.

**Closed** 2022-01-31 23:28 UTC
Labels: bug
